# Generated by Django 5.1.15 on 2026-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('system_a_rows_read', models.PositiveIntegerField(default=0)),
                ('system_a_rows_saved', models.PositiveIntegerField(default=0)),
                ('system_b_rows_read', models.PositiveIntegerField(default=0)),
                ('system_b_rows_saved', models.PositiveIntegerField(default=0)),
                ('location_rows_read', models.PositiveIntegerField(default=0)),
                ('location_rows_saved', models.PositiveIntegerField(default=0)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('invalid_values_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=255, unique=True)),
                ('organization_id', models.CharField(max_length=255)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id_raw', models.CharField(max_length=255)),
                ('record_id_normalized', models.CharField(db_index=True, max_length=255)),
                ('location_id', models.CharField(blank=True, default='', max_length=255)),
                ('value_raw', models.TextField(blank=True, default='')),
                ('value_parsed', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_parse_status', models.CharField(default='UNKNOWN', max_length=32)),
                ('source_row_number', models.PositiveIntegerField(default=0)),
                ('import_warning', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['record_id_normalized', 'location_id'], name='reconciliat_record__abf5d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ref_raw', models.CharField(max_length=255)),
                ('record_ref_normalized', models.CharField(db_index=True, max_length=255)),
                ('location_id', models.CharField(blank=True, default='', max_length=255)),
                ('value_raw', models.TextField(blank=True, default='')),
                ('value_parsed', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_parse_status', models.CharField(default='UNKNOWN', max_length=32)),
                ('source_row_number', models.PositiveIntegerField(default=0)),
                ('import_warning', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['record_ref_normalized', 'location_id'], name='reconciliat_record__f2c706_idx')],
            },
        ),
    ]
