# Generated by Django 5.1.15 on 2026-09-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='locations_malformed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='system_a_blank_values',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='system_a_invalid_values',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='system_a_malformed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='system_b_blank_values',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='system_b_invalid_values',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='system_b_malformed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='import_warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='malformed_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='malformed_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='raw_source_row',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='malformed_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='raw_source_row',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
